export const SET_PERSONALINFO = "SET_PERSONALINFO";
export const SET_WORKEXPERIENCE = "SET_WORKEXPERIENCE";
export const SET_EDUCATION = "EDUCATION";
export const SET_KEYSKILLS = "SET_KEYSKILLS";
export const SET_PROFILEPHOTO = "SET_PROFILEPHOTO";
